# Generated by Django 2.2.6 on 2019-10-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191014_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
